import{a as v,S as R}from"./assets/vendor-Bm5kWEQS.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&i(f)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const $="https://pixabay.com/api/",P="52417651-378a9ae18bca7d74fedb43ebe";async function y(r,t=1,o=12){const i=`${$}?key=${P}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${o}`;try{const e=await v.get(i);return{hits:e.data.hits||[],totalHits:e.data.totalHits||0}}catch(e){return console.error("Pixabay fetch error:",e),{hits:[],totalHits:0}}}let m;const h=document.querySelector(".loader");function S(r){r.innerHTML=""}function b(){h.style.display="block"}function d(){h.style.display="none"}function L(r,t,o=!0){const i=r.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags.replace(/"/g,"&quot;")}" width="300" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </li>
    `).join("");o?t.innerHTML=i:t.insertAdjacentHTML("beforeend",i),m?m.refresh():m=new R(".gallery a",{captionsData:"alt",captionDelay:250})}const g=document.querySelector(".form"),u=document.querySelector(".gallery"),a=document.querySelector(".load-more");document.querySelector(".loader");let l="",p=1;const w=12;let n=0,c=0;g.addEventListener("submit",async r=>{if(r.preventDefault(),l=g.elements["search-text"].value.trim(),!l){iziToast.warning({message:"Please enter a search term!",position:"topRight"});return}p=1,n=0,c=0,S(u),b(),a.style.display="none";try{const t=await y(l,p,w),o=t.hits;if(c=t.totalHits||0,!o||o.length===0){iziToast.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),d();return}L(o,u,!0),n+=o.length,n<c&&(a.style.display="inline-block")}catch(t){iziToast.error({message:"Sorry, something went wrong. Please try again later.",position:"topRight"}),console.error(t)}finally{d()}});a.addEventListener("click",async()=>{p++,b();try{const t=(await y(l,p,w)).hits;if(!t||t.length===0){iziToast.info({message:"You've reached the end of the results.",position:"topRight"}),a.style.display="none",d();return}L(t,u,!1),n+=t.length,n>=c&&(iziToast.info({message:"You've reached the end of the results.",position:"topRight"}),a.style.display="none");const o=u.firstElementChild;if(o){const{height:i}=o.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}}catch(r){iziToast.error({message:"Could not load more images.",position:"topRight"}),console.error(r)}finally{d()}});
//# sourceMappingURL=index.js.map
